/********************************************************************************
 * Copyright (c) 2023 CrossBreeze.
 ********************************************************************************/
import * as rpc from 'vscode-jsonrpc/node';

export const KDLRegex = {
   STRING: /^"[^"]*"$|^'[^']*'$/,
   NUMBER: /^(-)?[0-9]+(\.[0-9]*)?$/,
   SL_COMMENT: /^#[^\n\r]*$/,
   ID: /^[_a-zA-Z][\w_\-~$#@/\d$]*$/
};



/**
 * Serialized version of the semantic model generated by Langium.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const KDLTerminals = {
   STRING: /"[^"]*"|'[^']*'/,
   NUMBER: /(-)?[0-9]+(\.[0-9]*)?/,
   SL_COMMENT: /#[^\n\r]*/,
   INDENT: /:synthetic-indent:/,
   DEDENT: /:synthetic-dedent:/,
   LIST_ITEM: /- /,
   NEWLINE: /[/\r\n|\r|\n/]+/,
   WS: /[ \t]+/,
   ID: /[_a-zA-Z][\w_\-~$#@/\d]*/,
};

export type Reference<T> = string;


export type NodeType = ClusterNode | ContainerNode | IngressNode | PodNode | PortNode | ServiceNode;

export const NodeType = 'NodeType';

// Updated ClusterNode interface
export interface ClusterNode {
   readonly $type: 'ClusterNode';
   id: string;
   ingresses: Array<IngressNode>;
   name: string;
   pods: Array<PodNode>;
   services: Array<ServiceNode>;
}
export const ClusterNode = 'ClusterNode';

export interface ContainerNode {
   readonly $type: 'ContainerNode';
   id: string;
   links: Array<Reference<PortNode>>;
   name: string;
}
export const ContainerNode = 'ContainerNode';

export interface Diagram {
   readonly $type: 'Diagram';
   edgeAttributes: Array<EdgeAttribute>;
   nodeAttributes: Array<NodeAttribute>;
}
export const Diagram = 'Diagram';

export interface Dimensions {
   readonly $type: 'Dimensions';
   height: number;
   width: number;
   x: number;
   y: number;
}
export const Dimensions = 'Dimensions';

export interface EdgeAttribute {
   readonly $type: 'EdgeAttribute';
   id: string;
   sourceID: Reference<NodeType>;
   targetID: Reference<NodeType>;
}
export const EdgeAttribute = 'EdgeAttribute';

export interface IngressNode{
   readonly $type: 'IngressNode';
   host: string;
   id: string;
   links: Array<Reference<PortNode>>;
   name: string;
}
export const IngressNode = 'IngressNode';

// Updated KDLDiagram interface
export interface KDLDiagram {
   readonly $type: 'KDLDiagram';
   diagram?: Diagram;
   id: string;
   clusters: Array<ClusterNode>;
   name: string;
}
export const KDLDiagram = 'KDLDiagram';

export interface KDLRoot {
   readonly $type: 'KDLRoot';
   kdlDiagram: KDLDiagram;
}
export const KDLRoot = 'KDLRoot';

export interface NodeAttribute {
   readonly $type: 'NodeAttribute';
   dimensions: Dimensions;
   id: string;
   nodeID: Reference<NodeType>;
}
export const NodeAttribute = 'NodeAttribute';

// Updated PodNode interface
export interface PodNode{
   readonly $type: 'PodNode';
   containers: Array<ContainerNode>;
   id: string;
   name: string;
   ports: Array<PortNode>;
}
export const PodNode = 'PodNode';

export interface Point{
   readonly $type: 'Point';
   x: number;
   y: number;
}
export const Point = 'Point';

export interface PortNode {
   readonly $type: 'PortNode';
   id: string;
   name: string;
   number: number;
}
export const PortNode = 'PortNode';

export interface ServiceNode {
   readonly $type: 'ServiceNode';
   id: string;
   links: Array<Reference<PortNode>>;
   name: string;
   ports: Array<PortNode>;
}
export const ServiceNode = 'ServiceNode';


export interface ClientModelArgs {
   uri: string;
   clientId: string;
}

export interface OpenModelArgs extends ClientModelArgs {
   languageId?: string;
}

export interface CloseModelArgs extends ClientModelArgs {}

export interface UpdateModelArgs<T = KDLRoot> extends ClientModelArgs {
   model: T | string;
}

export interface SaveModelArgs<T = KDLRoot> extends ClientModelArgs {
   model: T | string;
}

export interface ModelDiagnostic {
   type: 'lexing-error' | 'parsing-error' | 'validation-error';
   message: string;
   severity: 'error' | 'warning' | 'info';
}

export namespace ModelDiagnostic {
   export function isError(diagnostic: ModelDiagnostic): boolean {
      return diagnostic.severity === 'error';
   }

   export function errors(diagnostics: ModelDiagnostic[]): ModelDiagnostic[] {
      return diagnostics.filter(isError);
   }

   export function hasErrors(diagnostics: ModelDiagnostic[]): boolean {
      return diagnostics.some(isError);
   }
}

export interface KDLDocument<T = KDLRoot, D = ModelDiagnostic> {
   uri: string;
   root: T;
   diagnostics: D[];
}
 
export interface ModelUpdatedEvent<D = KDLDocument> {
   document: D;
   sourceClientId: string;
   reason: 'changed' | 'deleted' | 'updated' | 'saved';
}

export interface ModelSavedEvent<D = KDLDocument> {
   document: D;
   sourceClientId: string;
}

/**
 * A context to describe a cross reference to retrieve reachable elements.
 */
export interface CrossReferenceContext {
   /**
    * The container from which we want to query the reachable elements.
    */
   container: CrossReferenceContainer;
   /**
    * Synthetic elements starting from the container to further narrow down the cross reference.
    * This is useful for elements that are being created or if the element cannot be identified.
    */
   syntheticElements?: SyntheticElement[];
   /**
    * The property of the element referenced through the source container and the optional synthetic
    * elements for which we should retrieve the reachable elements.
    */
   property: string;
}
export interface RootElementReference {
   uri: string;
}
export function isRootElementReference(object: unknown): object is RootElementReference {
   return !!object && typeof object === 'object' && 'uri' in object && typeof object.uri === 'string';
}
export interface GlobalElementReference {
   globalId: string;
   type?: string;
}
export function isGlobalElementReference(object: unknown): object is GlobalElementReference {
   return !!object && typeof object === 'object' && 'globalId' in object && typeof object.globalId === 'string';
}
export interface SyntheticDocument {
   uri: string;
   type: string;
}
export function isSyntheticDocument(object: unknown): object is SyntheticDocument {
   return (
      !!object &&
      typeof object === 'object' &&
      'uri' in object &&
      typeof object.uri === 'string' &&
      'type' in object &&
      typeof object.type === 'string'
   );
}
export type CrossReferenceContainer = RootElementReference | GlobalElementReference | SyntheticDocument;

export interface SyntheticElement {
   type: string;
   property: string;
}
export function isSyntheticElement(object: unknown): object is SyntheticElement {
   return (
      !!object &&
      typeof object === 'object' &&
      'type' in object &&
      typeof object.type === 'string' &&
      'property' in object &&
      typeof object.property === 'string'
   );
}
export interface ReferenceableElement {
   uri: string;
   type: string;
   label: string;
}

export interface CrossReference {
   /**
    * The container from which we want to resolve the reference.
    */
   container: CrossReferenceContainer;
   /**
    * The property for which we want to resolve the reference.
    */
   property: string;
   /**
    * The textual value of the reference we are resolving.
    */
   value: string;
}

export interface ResolvedElement {
   uri: string;
   model: KDLRoot;
}

export interface SystemInfoArgs {
   contextUri: string;
}

export interface SystemInfo {
   id: string;
   name: string;
   directory: string;
   packageFilePath: string;
   modelFilePaths: string[];
}

export interface SystemUpdatedEvent {
   system: SystemInfo;
   reason: 'added' | 'removed';
}
export type SystemUpdateListener = (event: SystemUpdatedEvent) => void | Promise<void>;

export const OpenModel = new rpc.RequestType1<OpenModelArgs, KDLDocument | undefined, void>('server/open');
export const CloseModel = new rpc.RequestType1<CloseModelArgs, void, void>('server/close');
export const RequestModel = new rpc.RequestType1<string, KDLDocument | undefined, void>('server/request');
export const RequestModelDiagramNode = new rpc.RequestType2<string, string, Element | undefined, void>('server/requestModelDiagramNode');

export const FindReferenceableElements = new rpc.RequestType1<CrossReferenceContext, ReferenceableElement[], void>('server/complete');
export const ResolveReference = new rpc.RequestType1<CrossReference, ResolvedElement | undefined, void>('server/resolve');

export const UpdateModel = new rpc.RequestType1<UpdateModelArgs, KDLDocument, void>('server/update');
export const SaveModel = new rpc.RequestType1<SaveModelArgs, void, void>('server/save');
export const OnModelSaved = new rpc.NotificationType1<ModelSavedEvent>('server/onSave');
export const OnModelUpdated = new rpc.NotificationType1<ModelUpdatedEvent>('server/onUpdated');

export const RequestSystemInfos = new rpc.RequestType1<void, SystemInfo[], void>('server/systems');
export const RequestSystemInfo = new rpc.RequestType1<SystemInfoArgs, SystemInfo | undefined, void>('server/system');
export const OnSystemsUpdated = new rpc.NotificationType1<SystemUpdatedEvent>('server/onSystemsUpdated');
